language: node_js
script: npm test
node_js:
- '0.12'
before_install:
- openssl aes-256-cbc -K $encrypted_183dece04d47_key -iv $encrypted_183dece04d47_iv
  -in key.priv.enc -out key.priv -d
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
addons:
    firefox: "39.0"
before_deploy:
  - node build
  - node_modules/.bin/deploy
deploy:
  skip_cleanup: true
  provider: script
  script: bin/deploy.sh
env:
  global:
  - secure: VECjYM3mLDDTZFp7TXcp5hpIsFRpxcRW4n4TtF5hSaT7zBAptHd+k+H+XUNDl+g8ZtY05veeh7i4eYtuXlm1A1vloMvhajF70WCa6prR+0SPj0BGPZYkQN+AXEowQfiIOpPnCxRqn3rvNscOZOyWDIz8s8rg9obPSkLu4JT1VcN250x7vtlyUi19VUiOVQs7E8yIF2uZ920JoV11OKxt9MumDYKeBtXUNf2fxacCjXE2v0FOuQJ2rEolEjotiEWco66Y88CVmHvp0CHm4+9MPny88j7KQNZi6TE4z/Zhoti1o13SEF7ThVEAK+ZlTKIvDscOblyEtjDF/QT1uhViQLxLmorO0ClcluXJfFaaasRjWxawESPL4pdqEEf3vNR5BFb3ckPe9WlGySKBgD27SZIAeZP20wBIc1S2UCN66qiRm0+Ujlt11PdPiv0Qso8teRQGjRM9fkDGBxdPKeWTwfacQgIDyF+DlnURZec0DUv2jf5lvPADAqNHfnELocg0F5tPpx45cqIAoxQPV2kbfIwZsj/ntcdlhsWIik8w1d3L5JqVixrQLRpSLv5h0X8hd0afadkPSBaOBUnKmROWtT6rZEsy6ozxn9NBFl8nT/IqQBAax0D2XYsa6SoBRyKP2c/jvP/Rjjz48vAp34DwP1dx8dk5o9yuxpYZtlIjhMQ=
  - secure: V+EclFuxNby00y+TboV/lBXjRG/2WCCqM96sPN+OpXcEYQFhP2zJwXAJv9YvVIREYhEZBKBpoKhlKkiScC5Oq11YbVAnkUHcu4AcsUXt5KCPsC5FtoB85Yu8KrjN6A1z7OfJ8S/h6O9ujhVNrfNsaDEq0YpZ6fk6Y9TuWwC5c/nREPxhS4ciAKw81l0786XbQ3fTdKSbxwEW/DRiFEZaYwazsxxg4jWWMaywtkkdBCiL4uBh/HjerF9+e1gd/JEx4x8b41xYYqGMVrkthusDH++OG/XW6rDUSXRCq4Y0NTFGvkFKyXG5NzK6CUmzOvu+KUakSwj2UsJldpiUeuyZJIOxnDmgxAl8a1eiB4eiFqs9X/x7jZyH+TdkCYZGNqdjaWr1j/XqHAP9PLqW00KkQkI5+T1Xrl+bLKYsydPoIF9dzPUKdiPFqlyS67n9+KqaHvHcG8EH0PvJKioeQpKBXBXYImaBsivxXhtMFc/DOtDrIvAcArrow1+2k04ubKm/i0d+BPVJOl0o5NkJ3PC8/NaMWJkJ+M8s6JhaSqjTsDiTFTsyuIKOlc0kKkodj3ayziGr75wLfNWk+/l4DGQ43pCPA03BeyCF4LbhvTg6eZHWjN+C7F881fWJ33iVPyehnwGqRoyx0su3Oa+O1cZz+ltyfl1MF2AJE7RuvRtzkVo=
  - secure: Mc4Tc3YSe3D/I1OIM+lEOfoHHVZKz97kTCKWgKjdvDNfRNX6KFa7vCS9qPIONJH7IMgpeM4GmN+Ng4YNUkRoKXW6WO2GjzvqUjNfZM0DfRDbUmLOvrxaZTfylhnLWpVS788nMzKPV9C7mjKC56mxP7V+zJrLQNcCjqRe0zlM/3zFs5YzEVjkjlpn0xvt8cf5uvUjr8B3LqMKMFFrKrTd0RmwTby3RCp+qV6a2BX9yXnHAQLrDg4AJQAaKSPldmzjN/Hc8iGtX7+vgm92EDWsAIWJoWImZH0KYGJW9eIj2GbaoUSY9fjCMhja2hWTMQMzAF8Hj+mHx/VkwSdq+DDQDfhPBfLOQkXDlJ1YbT4c7+jDdBApgVA566epQigKZiLZ6TpC1NXqe0bvjN2pt/RJ0HRJTCSky3UQswyf1ranYsZeXqbKNI9wdoPqnVCAoDwq6+Z395giyofzTkj6fn6w2j42V6UxPzvAe5v/beKhpfN5e4toXnh8If17ZZxYOhZxC4yJ+JkoAX/MswpwDSPPGgG+YFarzUAvGZOFOodm9M4g/AZjifd2np01O2xFe9N3j7KZeoz6559oMEUUINXV4tetQGSQtpUx6HEamq1wEVYhDCnfM+bPrWu2jp7/mT3TB/TLrS4Stx4p9W//Vz7ciKEEINlEPnuNLeomzm49tCo=
